baseURL = 'https://smilingmiao.github.io/blog/'
languageCode = 'zh-cn'
title = "ğŸŒ"
theme = "hugo-book"

disablePathToLower = true
googleAnalytics = 'G-MEASUREMENT_ID'

[markup]
[markup.goldmark.renderer]
  unsafe = true
  
[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = '*'
  BookSearch = true
  
